# Tasca 4: Programació numèrica

Roger Gallart

20 Abril 2021

In [90]:
import numpy as np
from scipy import stats

## Nivell 1

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [91]:
def resum_estadistic(array):
  '''
  Retorna un resum estadístic bàsic de les dades del vector (ndarray 1D).
  Paràmetres:
    vector (ndarray 1D)
  Retorna:
    resum (Diccionari)
    missatge d'error si dimensió és > 1D
  '''

  if array.ndim > 1:
    return 'Error: el paràmetre d\'entrada no pot tenir més de una dimensió'
  
  return stats.describe(array) # Utilitzem el mòdul stats de Scipy


In [92]:
# Test 1
test1 = np.random.randn(10,) # 1D, Standard normal distribution, 10 elements
print(f'test1:\n {test1}')
print(f'Resum estadistic de test1:\n',resum_estadistic(test1))

# Test 2
test2 = np.random.randn(10,10) # 2D
print(f'\ntest2:\n {test2}')
print(f'Resum estadistic de test1:\n',resum_estadistic(test2))


test1:
 [ 1.27737871  0.34300937 -1.10752024  0.72730169  0.26763647 -1.19339417
  1.24158984  0.10363987  0.29625393 -0.71448884]
Resum estadistic de test1:
 DescribeResult(nobs=10, minmax=(-1.1933941748937, 1.277378705957841), mean=0.1241406604086027, variance=0.7774641967444894, skewness=-0.2696460382453283, kurtosis=-1.1059838151440071)

test2:
 [[-3.12650029e-01  6.26793738e-01 -1.02545425e-02 -5.51561531e-01
  -1.59818356e+00 -8.49847331e-01  6.92342300e-01  4.82092638e-01
   1.23591318e+00 -1.91054265e-01]
 [ 9.47902086e-01 -2.49788799e-01  2.16333750e+00  1.87705668e-01
   1.00666596e+00  2.32360139e-01  1.51464823e-03  3.43097431e-01
  -3.49414417e-01  3.66664254e-01]
 [-1.50985509e-01 -3.78611130e-01  1.87609750e-01 -9.01206617e-01
  -1.09886117e+00  7.64313239e-01 -2.53482436e-01 -1.29850903e+00
   1.36862302e+00 -1.19485678e+00]
 [-2.65952652e-01  6.03170653e-01  2.02316040e-01 -3.46251210e-01
   1.20474511e+00 -9.36795221e-01 -7.98122039e-01 -3.63573016e-01
   7.15081322e-

### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [93]:
def matriu_aleatoria(N):
  '''
  Genera una matriu 2D (ndarray) de NxN nombres enters aleatoris entre 0 i 100
  seguint una distribució unifome
  '''
  return np.random.randint(0,101,size=(N,N)) 
  # Posem 101 perquè aquesta funció de numpy no inclou el límit superior

In [94]:
# Test
for N in range(1,5):
  print(f'Matriu aleatòria de {N}x{N}:')
  print(matriu_aleatoria(N),'\n')

Matriu aleatòria de 1x1:
[[7]] 

Matriu aleatòria de 2x2:
[[71 82]
 [75 87]] 

Matriu aleatòria de 3x3:
[[33 45 62]
 [21 34 31]
 [ 1 63 21]] 

Matriu aleatòria de 4x4:
[[44  1  2 13]
 [43 27 15 88]
 [41 60 22  9]
 [75  1 29 55]] 



### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [95]:
def totals(matriu):
  '''
  Donada una matriu numèrica, calcula els totals per cada fila i per cada columna
  
  Paràmetres:
    matriu (ndarray de 2D)
  
  Retorna:
    totals_files (ndarray de 1D)
    totals_columnes (ndarray de 1D)
  '''

  totals_files = np.sum(matriu, axis=1)
  totals_columnes = np.sum(matriu, axis=0)

  return totals_files, totals_columnes

In [96]:
# Test
test = matriu_aleatoria(6) #Utilitzem la funció de l'exercici 2
resultat = totals(test)

print(f'Matriu de test:\n {test}')
print(f'\nTotals de cada fila: {resultat[0]}')
print(f'\nTotals de cada columna: {resultat[1]}')

Matriu de test:
 [[66 61 87 60 27 72]
 [18  9 30 56 98  0]
 [ 8 95 81 22 17 59]
 [96 74 50 64 67 99]
 [ 5 51 10 33 57 53]
 [ 9 52 53 94  3 38]]

Totals de cada fila: [373 211 282 450 209 249]

Totals de cada columna: [202 342 311 329 269 321]


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [97]:
def coef_correlacio(x,y):
  '''
  Calcula manualment el coeficient de correlació de Pearson de 2 variables x i y
  Formula: r = cov(x,y)/(s_x*s_y) essent:
    - cov(x,y) la covariança entre x i y
    - s_x i s_y la desviació estandar de x i y respectivament

  Paràmetres:
    x, y: vectors (ndarray 1D) amb N elements
  
  Retorna:
    r: coeficient de correlació de Pearson
  '''

  # Nombre de elements de la mostra
  N = len(x)

  # Mitjana mostral
  avg_x = np.sum(x)/N
  avg_y = np.sum(y)/N

  # Desviació estándar mostral (Graus de Llibertat = 1 --> Dividim per N-1)
  s_x = np.sqrt(np.sum((x-avg_x)**2)/(N-1))  
  s_y = np.sqrt(np.sum((y-avg_y)**2)/(N-1))

  # Covariança
  cov_xy = np.sum(np.multiply(x-avg_x,y-avg_y))/(N-1)

  # Coefficient de correlació
  r = cov_xy/(s_x*s_y)
  
  return r

In [98]:
# Test 1 - Correlació entre 2 vectors alreatoris x i y

x = np.random.randn(10,) # 1D, Standard normal distribution, 10 elements
y = np.random.randn(10,) # 1D, Standard normal distribution, 10 elements
print(f'x:\n {x}')
print(f'y:\n {y}')
print(f'\nEl coeficient de correlació entre x i y usant la nostra funció: {coef_correlacio(x,y)}')
print(f'El coeficient de correlació entre x i y usant la funció de numpy: {np.corrcoef(x,y)[0,1]}')


x:
 [ 0.68034425  0.83388918  0.52442922 -0.35939249 -1.15076663 -1.29984124
  0.03071062  0.65187744 -1.26054198  0.2283436 ]
y:
 [ 1.71121592  0.08319077  0.47212565 -0.75073587  1.36381399  0.29820203
  0.46611847 -1.64837324  0.98631234 -0.09683166]

El coeficient de correlació entre x i y usant la nostra funció: -0.292337720687766
El coeficient de correlació entre x i y usant la funció de numpy: -0.2923377206877659


In [99]:
# Test 2 Correlació d'un vector amb ell mateix ha de ser 1

x = np.random.randn(10,) # 1D, Standard normal distribution, 10 elements
print(f'x:\n {x}')
print(f'\nEl coeficient de correlació de x amb ell mateix usant la nostra funció: {coef_correlacio(x,x)}')
print(f'El coeficient de correlació de x amb ell mateix usant la funció de numpy: {np.corrcoef(x,x)[0,1]}')


x:
 [-1.65353823  0.63733434 -0.53664276 -0.79887467  2.23471298  0.02825244
  0.27977452  0.60508622  1.2094965   2.34815578]

El coeficient de correlació de x amb ell mateix usant la nostra funció: 1.0000000000000002
El coeficient de correlació de x amb ell mateix usant la funció de numpy: 1.0
